Update app.py
fixed this error: File "/mount/src/glofi/app.py", line 226
      if st.session_state['enriched_df'] is not None:
     ^
SyntaxError: expected 'except' or 'finally' block

By adding the missing code.